/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as SettingsImport } from "./routes/settings";
import { Route as RegisterImport } from "./routes/register";
import { Route as ProtectedImport } from "./routes/protected";
import { Route as LoginImport } from "./routes/login";
import { Route as AccountImport } from "./routes/account";
import { Route as IndexImport } from "./routes/index";

// Create/Update Routes

const SettingsRoute = SettingsImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRoute,
} as any);

const RegisterRoute = RegisterImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRoute,
} as any);

const ProtectedRoute = ProtectedImport.update({
  id: "/protected",
  path: "/protected",
  getParentRoute: () => rootRoute,
} as any);

const LoginRoute = LoginImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRoute,
} as any);

const AccountRoute = AccountImport.update({
  id: "/account",
  path: "/account",
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/account": {
      id: "/account";
      path: "/account";
      fullPath: "/account";
      preLoaderRoute: typeof AccountImport;
      parentRoute: typeof rootRoute;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginImport;
      parentRoute: typeof rootRoute;
    };
    "/protected": {
      id: "/protected";
      path: "/protected";
      fullPath: "/protected";
      preLoaderRoute: typeof ProtectedImport;
      parentRoute: typeof rootRoute;
    };
    "/register": {
      id: "/register";
      path: "/register";
      fullPath: "/register";
      preLoaderRoute: typeof RegisterImport;
      parentRoute: typeof rootRoute;
    };
    "/settings": {
      id: "/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof SettingsImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/account": typeof AccountRoute;
  "/login": typeof LoginRoute;
  "/protected": typeof ProtectedRoute;
  "/register": typeof RegisterRoute;
  "/settings": typeof SettingsRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/account": typeof AccountRoute;
  "/login": typeof LoginRoute;
  "/protected": typeof ProtectedRoute;
  "/register": typeof RegisterRoute;
  "/settings": typeof SettingsRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/account": typeof AccountRoute;
  "/login": typeof LoginRoute;
  "/protected": typeof ProtectedRoute;
  "/register": typeof RegisterRoute;
  "/settings": typeof SettingsRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/account"
    | "/login"
    | "/protected"
    | "/register"
    | "/settings";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/account" | "/login" | "/protected" | "/register" | "/settings";
  id:
    | "__root__"
    | "/"
    | "/account"
    | "/login"
    | "/protected"
    | "/register"
    | "/settings";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AccountRoute: typeof AccountRoute;
  LoginRoute: typeof LoginRoute;
  ProtectedRoute: typeof ProtectedRoute;
  RegisterRoute: typeof RegisterRoute;
  SettingsRoute: typeof SettingsRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  LoginRoute: LoginRoute,
  ProtectedRoute: ProtectedRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/account",
        "/login",
        "/protected",
        "/register",
        "/settings"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/account": {
      "filePath": "account.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/protected": {
      "filePath": "protected.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/settings": {
      "filePath": "settings.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
